"""img_key added to product and variat models

Revision ID: 828d4b89b219
Revises: 9588004b9a11
Create Date: 2026-02-03 11:48:03.865492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828d4b89b219'
down_revision: Union[str, Sequence[str], None] = '9588004b9a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admins_username_key'), 'admins', type_='unique')
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.add_column('product_variants', sa.Column('img_key', sa.String(), nullable=True))
    op.drop_column('product_variants', 'img_url')
    op.add_column('products', sa.Column('img_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img_key')
    op.add_column('product_variants', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product_variants', 'img_key')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.create_unique_constraint(op.f('admins_username_key'), 'admins', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
