"""add_cascade_delete_to_product_variants

Revision ID: 88eea78adab4
Revises: 828d4b89b219
Create Date: 2026-02-04 20:15:12.788623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88eea78adab4'
down_revision: Union[str, Sequence[str], None] = '828d4b89b219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_variants_product_id_fkey'), 'product_variants', type_='foreignkey')
    op.create_foreign_key(None, 'product_variants', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.create_foreign_key(op.f('product_variants_product_id_fkey'), 'product_variants', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
