"""removed category-id

Revision ID: 9310513b4350
Revises: eb1fe60dc2b3
Create Date: 2026-01-30 16:37:17.694148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9310513b4350'
down_revision: Union[str, Sequence[str], None] = 'eb1fe60dc2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###
