"""updated product model

Revision ID: d6a1a19a4437
Revises: f3e57bdd1745
Create Date: 2026-01-21 16:15:43.071316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a1a19a4437'
down_revision: Union[str, Sequence[str], None] = 'f3e57bdd1745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('product', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'stock')
    op.drop_column('product', 'price')
    # ### end Alembic commands ###
