"""add hashed password to admins

Revision ID: dd03f8fe0035
Revises: 88eea78adab4
Create Date: 2026-03-10 22:42:54.632941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd03f8fe0035'
down_revision: Union[str, Sequence[str], None] = '88eea78adab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable so existing rows don't violate NOT NULL.
    op.add_column('admins', sa.Column('hashed_password', sa.String(), nullable=True))

    # Step 2: Delete any existing admin rows — they have no password hash
    # and cannot log in securely anyway. Re-create admins after migrating.
    op.execute("DELETE FROM admins")

    # Step 3: Now that all rows are gone, enforce NOT NULL safely.
    op.alter_column('admins', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'hashed_password')
    # ### end Alembic commands ###
